#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DevOpsCulture
subtitle: KPIs can drive culture
author: Anthony McLin
email: your-email@example.com
avatar: https://avatars3.githubusercontent.com/u/105728?s=460&v=4
description: >- # this means to ignore newlines until "baseurl:"
  DevOps requires a change in organization culture, not just implementing technologies. Discover
  new KPIs for digital business success.
baseurl: "/devopsculture" # the subpath of your site, e.g. /blog
url: "https://amclin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: anthony_mclin
github_username:  amclin

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url: https://twitter.com/anthony_mclin
linkedin_url: https://www.linkedin.com/in/anthonymclin/
github_url: https://github.com/amclin/devopsculture

# Build settings
exclude: ["Gemfile*", "Rakefile"]
markdown: kramdown
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-feed

collections:
  sections:
    output: true
  kpis:
    output: true
  kpis-proposed:
    output: true

# Google Analytics Tracking ID goes here:
google_analytics:
